# This Workflow Builds, Tests, Lints, and Deploys the UI to Heroku
name: CI/CD for Main branch's UI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main]
        paths:
            - "ui/**"
    pull_request:
        branches: [main]
        paths:
            - "ui/**"

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# 'jobs' is the list of all the workflows that will kick off.
jobs:
    # This workflow kicks off the build and test for the UI
    build-and-test:
        # Name of the build job
        name: Build and Test UI
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # `steps` are the actions that will execute on this job.
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
            # Runs a single command using the runners shell to build the UI
            - name: Build UI
              run: |
                  docker build -f ./ui.Dockerfile -t bloggly-ui .
            # Runs a set of commands using the runners shell to test the UI
            - name: Test UI
              run: |
                  docker run -e CI=true bloggly-ui yarn run test

    # This workflow kicks off the linter for UI.
    lint:
        name: Lint UI Code Base
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            # Installs dependencies on the runner for UI
            - name: Install linter options
              run: yarn workspace ui install
            # Executes the linter on the UI code base.
            - name: Run Linter
              run: yarn workspace ui run lint

    # This workflow kicks off the deployment to Heroku for the UI
    deploy:
        name: Deploy UI to Heroku
        # Needs specifies the steps that must previously complete in order to deploy your application.
        needs: [lint, build-and-test]
        # Only deploy after merge with main
        if: github.event_name == 'push'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Use Node.js 17.x
              uses: actions/setup-node@v1
              with:
                  node-version: 17.x

            - name: Build UI
              run: |
                  yarn workspace ui install
                  yarn workspace ui run build
            - name: CompressFiles
              uses: stefh/ghaction-CompressFiles@v2
              with:
                  path: "ui/dist"

            - name: Commit Build
              run: |
                  git config --local user.email "actions@users.noreply.github.com"
                  git config --local user.name "Automated Publisher"
                  git add -f ui/dist/*
                  git commit -m "Chore: Build UI for distribution"

            - name: Deploy UI
              uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "bloggly-ui"
                  heroku_email: "dkarrick2@gmail.com"
                  appdir: "ui"
                  buildpack: "https://github.com/heroku/heroku-buildpack-static.git"
                  branch: main
